apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp
  #namespace: ar
spec:
  project: default
  source:
    repoURL: https://github.com/Aniketsabharwal001/argocd.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
