apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp
  #namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Aniketsabharwal001/argocd.git
    targetRevision: master
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true          # cleans up deleted resources
      selfHeal: true       # auto-corrects drift
    syncOptions:
      - CreateNamespace=true
      - FailFast=true      # stops sync immediately if any resource fails
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas   # ✅ Ignores replica changes (you can scale manually without showing OutOfSync)
