apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp
spec:
  project: default
  source:
    repoURL: https://github.com/Aniketsabharwal001/argocd.git
    targetRevision: master
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true          # optional: cleans up deleted resources
      selfHeal: true       # optional: auto-corrects drift
    syncOptions:
      - CreateNamespace=true
      - FailFast=true       # ✅ stops sync immediately if any resource fails
